name = "Tomography"
uuid = "7b913008-954d-4a4c-99e7-286cce9c5096"
authors = ["physimatics <bbbcaobb@gmail.com>"]
version = "0.1.2"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"